# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Advent of Code Walkthroughs
description: Dazbo's Advent of Code solutions, written in Python

# We need the URLs below otherwise overriding CSS wont work
repository: derailed-dash/derailed-dash.github.io
# baseurl: /Advent-of-Code  # should not contain host!
baseurl: /
# url: https://derailed-dash.github.io
url: https://aoc.just2good.co.uk

twitter_username: DerailedDash
github_username:  Derailed-Dash
author: Dazbo

# Build settings
theme: jekyll-theme-modernist
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - docker-compose.yml
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
  - scope:
      path: ""  # Everything
    values:
      layout: "day-page"  # most of our pages will use this layout; use default for index
      topic: "Advent of Code"
  - scope:  # exclude the domain ownership verification from sitemap
      path: google*.html
    values:
      sitemap: false
  - scope:
      path: "python"
    values:
      layout: "journey-page" 
      topic: "The Python Journey"
  - scope:
      path: "2015"  # only apply to files in this folder
    values:
      year: 2015
  - scope:
      path: "2021"  # only apply to files in this folder
    values:
      year: 2021
