# override site.url when running in Docker, since Jekyll sets host to 0.0.0.0
# to allow the container to be accessible, but this breaks any absolute links in the site
# Then, be sure to explicitly specify config files when running jekyll serve from a container
# I.e. jekyll serve --config _config.yml,_config.docker.yml
# It is also necessary to set JEKYLL_ENV to anything other than default of "development",
# such that Jekyll listens on 0.0.0.0 without also overriding the server address to http://0.0.0.0:4000
url: "http://localhost:4000" # override server address, rather than using container "listen" address
force_polling: true  # Force watch to use polling, otherwise changes may not be noticed