version: '3.9'
services:
  jekyll-aoc:
    environment:
      - JEKYLL_ENV=docker
    command: jekyll serve --force-polling --watch --incremental --config  _config.yml,_config.docker.yml
    image: jekyll/jekyll
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    ports:
      - 127.0.0.1:4000:4000