version: '3.9'
services:
  jekyll-aoc:
    environment:
      - JEKYLL_ENV=docker # to stop Jekyll from overriding site.url to http://0.0.0.0:4000
      - JEKYLL_GITHUB_TOKEN
    command: >
      /bin/bash -c "echo 'Starting Jekyll server at http://127.0.0.1:4000' &&
      jekyll serve --watch --config _config.yml,_config.docker.yml"
    image: daz502/jekyll:0.1    
    # image: jekyll/jekyll
    container_name: dazbo-jekyll-aoc
    volumes:
      - .:/srv/jekyll
      - ..:/srv # to map the project folder that contains the Git repo
      - ./vendor/bundle:/usr/local/bundle  # to cache bundle configuration
    ports:
      - 127.0.0.1:4000:4000
